### ISSUE TITLE
Build failure on kernel 7.2 (clang: implicit declarations, remain_on_channel signature mismatch)

### ISSUE THREAD

**Issue by ronnyf** [ronnyf/AIC8800-Linux-Driver#16]
## Symptoms

DKMS module fails to build on kernel 7.2 (e.g. CachyOS `7.2.0-1-cachyos`) with clang:

```
aic8800_fdrv/rwnx_msg_tx.c:4709:5: error: call to undeclared library function 'strncpy' with type 'char *(char *, const char *, __size_t)' (aka 'char *(char *, const char *, unsigned long)'); ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

aic8800_fdrv/rwnx_main.c:6191:26: error: incompatible function pointer types initializing 'int (*)(struct wiphy *, struct wireless_dev *, struct ieee80211_channel *, unsigned int, u64 *, const u8 *)' with an expression of type 'int (struct wiphy *, struct wireless_dev *, struct ieee80211_channel *, unsigned int, u64 *)' [-Wincompatible-function-pointer-types]
```

## Root Cause

Two issues:

1. **Missing `#include <linux/string.h>`** in `rwnx_msg_tx.c` — clang 17+ enforces that all library functions must have explicit declarations (no implicit function declarations). `strncpy` is used but the header is missing.

2. **`cfg80211_ops.remain_on_channel` signature changed** in kernel 7.2 — a new `const u8 *rx_addr` parameter was added to the callback. The driver's callback doesn't match the expected signature.

## Fix

See PR #15: https://github.com/ronnyf/AIC8800-Linux-Driver/pull/15

## Affected

- Kernel 7.2+ (confirmed on CachyOS 7.2.0-1-cachyos x86_64)
- Compiler: clang (auto-detected by Makefile on CachyOS)
