### PR TITLE
fix: add kernel 7.1+ cfg80211 API compatibility

### LINKED ISSUE #11: Build fails on kernel 7.1+: cfg80211_ops changed from net_device* to wireless_dev*, ieee80211_mgmt union flattened
### Problem

The driver fails to build against Linux kernel 7.1.3 (and likely 7.1+ in general) with 16 compilation errors. The kernel cfg80211 API changed between 6.x and 7.x in two breaking ways:

1. **`cfg80211_ops` callback signatures changed** — all station/key management callbacks now take `struct wireless_dev *wdev` instead of `struct net_device *netdev`.
2. **`struct ieee80211_mgmt` unnamed union nesting was flattened** — `mgmt->u.action.u.tdls_*` became `mgmt->u.action.tdls_*`.

### Errors

**`rwnx_main.c`** (12 errors):
```
error: incompatible pointer types passing 'struct net_device *' to parameter of type 'struct wireless_dev *'
  3235: cfg80211_new_sta(rwnx_vif->ndev, ...)
  3351: cfg80211_del_sta(rwnx_vif->ndev, ...)

error: incompatible function pointer types initializing cfg80211_ops callbacks:
  6061: .add_key = rwnx_cfg80211_add_key          (expects net_device*, kernel wants wireless_dev*)
  6062: .get_key = rwnx_cfg80211_get_key
  6063: .del_key = rwnx_cfg80211_del_key
  6065: .set_default_mgmt_key = rwnx_cfg80211_set_default_mgmt_key
  6066: .add_station = rwnx_cfg80211_add_station
  6067: .del_station = rwnx_cfg80211_del_station_compat
  6068: .change_station = rwnx_cfg80211_change_station
  6083: .get_station = rwnx_cfg80211_get_station
  6174: rwnx_cfg80211_ops.get_station = ...
  6175: rwnx_cfg80211_ops.dump_station = ...
```

**`rwnx_tdls.c`** (4 errors):
```
error: no member named 'u' in 'struct ieee80211_mgmt::(unnamed union)::(unnamed at ...)'
  118: mgmt->u.action.u.tdls_discover_resp
  120: mgmt->u.action.u.tdls_discover_resp.action_code
  121: mgmt->u.action.u.tdls_discover_resp.dialog_token
  122: mgmt->u.action.u.tdls_discover_resp.capability
```

**`rwnx_events.h`** (related):
```
  192: mgmt->u.action.u.wme_action.action_code
```

### Kernel API changes (7.1+)

**`include/net/cfg80211.h`** — `cfg80211_new_sta` / `cfg80211_del_sta`:
```c
// OLD (6.x and earlier)
void cfg80211_new_sta(struct net_device *dev, const u8 *mac_addr,
                      struct station_info *sinfo, gfp_t gfp);

// NEW (7.1+)
void cfg80211_new_sta(struct wireless_dev *wdev, const u8 *mac_addr,
                      struct station_info *sinfo, gfp_t gfp);
```

**`cfg80211_ops`** — all station/key callbacks changed `struct net_device *dev` to `struct wireless_dev *wdev`:
- `.add_key` / `.get_key` / `.del_key` / `.set_default_mgmt_key`
- `.add_station` / `.del_station` / `.change_station` / `.get_station` / `.dump_station`

**`include/linux/ieee80211.h`** — `struct ieee80211_mgmt` union was restructured:
```c
// OLD (6.x): mgmt->u.action.u.tdls_discover_resp
// NEW (7.1+): mgmt->u.action.tdls_discover_resp
```

### Suggested fix

Add kernel version guards in `rwnx_compat.h` and update the affected functions:

1. **`rwnx_compat.h`**: Add version checks for `KERNEL_VERSION(7, 1, 0)` for:
   - `cfg80211_new_sta` / `cfg80211_del_sta` call sites (pass `rwnx_vif->wdev` instead of `rwnx_vif->ndev`)
   - `ieee80211_mgmt` member access (remove inner `.u`)

2. **`rwnx_main.c`**: Update callback function signatures for kernel >= 7.1:
   - Change `struct net_device *netdev` / `struct net_device *dev` to `struct wireless_dev *wdev` in:
     `rwnx_cfg80211_add_key`, `rwnx_cfg80211_get_key`, `rwnx_cfg80211_del_key`,
     `rwnx_cfg80211_set_default_mgmt_key`, `rwnx_cfg80211_add_station`,
     `rwnx_cfg80211_del_station_compat`, `rwnx_cfg80211_change_station`,
     `rwnx_cfg80211_get_station`, `rwnx_cfg80211_dump_station`
   - Inside each function, derive `netdev` from `wdev` using `netdev_from_wdev(wdev)`

3. **`rwnx_tdls.c`**: Update `mgmt->u.action.u.tdls_*` to `mgmt->u.action.tdls_*` for kernel >= 7.1

4. **`rwnx_events.h`**: Update `mgmt->u.action.u.wme_action.action_code` to `mgmt->u.action.wme_action.action_code` for kernel >= 7.1

### Environment
- Kernel: 7.1.3-2-cachyos (x86_64, clang 22.1.6)
- Driver: aic8800-fdrv-dkms/6.4.3.0
- Builds fine on kernel 6.18.x

### PR DESCRIPTION
**Pull request by ronnyf**
### Problem

The driver fails to build against Linux kernel 7.1+ with 16 compilation errors. The kernel cfg80211 API changed in two breaking ways:

1. **`cfg80211_ops` callback signatures changed** — all station/key management callbacks now take `struct wireless_dev *wdev` instead of `struct net_device *netdev`
2. **`struct ieee80211_mgmt` union was flattened** — `mgmt->u.action.u.tdls_*` became `mgmt->u.action.tdls_*`

### Changes

- **`rwnx_compat.h`**: Added `KERNEL_VERSION(7, 1, 0)` guards with compat macros for `cfg80211_new_sta_call`, `cfg80211_del_sta_call`, and `mgmt_action_field`
- **`rwnx_main.c`**: Updated 9 callback function signatures (`add_key`, `get_key`, `del_key`, `set_default_mgmt_key`, `add_station`, `del_station_compat`, `change_station`, `get_station`, `dump_station`) to accept `struct wireless_dev *wdev` for kernel ≥ 7.1, derived `rwnx_vif` via `container_of()`
- **`rwnx_tdls.c`**: Updated `mgmt->u.action.u.*` → `mgmt_action_field(mgmt, *)` for kernel ≥ 7.1
- **`rwnx_events.h`**: Same `mgmt_action_field()` macro for tracepoint

### Build verified

- ✅ Builds on kernel 6.18.38-2-cachyos-lts (current system)
- Should fix kernel 7.1.3-2-cachyos (reported issue)

### Related

Fixes #11

### CODE REVIEW

**Review by ronnyf — COMMENTED** [review]
LGTM
